--#SET TERMINATOR @
CREATE PROCEDURE UPDATE_LEADERS_SCORE (
    IN in_School_ID INTEGER, 
    IN in_Leader_Score INTEGER
    )
  
LANGUAGE SQL
MODIFIES SQL DATA

BEGIN
	UPDATE CHICAGO_PUBLIC_SCHOOLS
	SET LEADERS_SCORE = in_Leader_Score
	WHERE SCHOOL_ID = in_School_ID;
END 
@