--#SET TERMINATOR @
CREATE PROCEDURE UPDATE_LEADERS_SCORE (
    IN in_School_ID INTEGER, 
    IN in_Leader_Score INTEGER
    )
  
LANGUAGE SQL
MODIFIES SQL DATA

BEGIN
	CALL SYSPROC.ADMIN_CMD('REORG TABLE CHICAGO_PUBLIC_SCHOOLS');
		IF in_Leader_Score BETWEEN 80 AND 99 THEN
			UPDATE CHICAGO_PUBLIC_SCHOOLS 
			SET LEADERS_SCORE = in_Leader_Score, LEADERS_ICON = 'Ve St'
			WHERE SCHOOL_ID = in_School_ID;
		ELSEIF in_Leader_Score BETWEEN 60 AND 79 THEN
			UPDATE CHICAGO_PUBLIC_SCHOOLS 
			SET LEADERS_SCORE = in_Leader_Score, LEADERS_ICON = 'St'
			WHERE SCHOOL_ID = in_School_ID;
		ELSEIF in_Leader_Score BETWEEN 40 AND 59 THEN
			UPDATE CHICAGO_PUBLIC_SCHOOLS 
			SET LEADERS_SCORE = in_Leader_Score, LEADERS_ICON = 'Avg'
			WHERE SCHOOL_ID = in_School_ID;		
		ELSEIF in_Leader_Score BETWEEN 20 AND 39 THEN
			UPDATE CHICAGO_PUBLIC_SCHOOLS 
			SET LEADERS_SCORE = in_Leader_Score, LEADERS_ICON = 'Wk'
			WHERE SCHOOL_ID = in_School_ID;	
		ELSEIF in_Leader_Score BETWEEN 0 AND 19 THEN
			UPDATE CHICAGO_PUBLIC_SCHOOLS 
			SET LEADERS_SCORE = in_Leader_Score, LEADERS_ICON = 'Ve Wk'
			WHERE SCHOOL_ID = in_School_ID;	
		ELSEIF in_Leader_Score < 0 THEN
			ROLLBACK WORK;
		ELSE 
			COMMIT WORK;
		END IF;
END
@